class FileService:
    def __init__(): ...

    def create_file(): ...

    def create_file_chunks(): ...

    def get_file_chunks(): ...

    def get_file(): ...

    def get_closest_chunks(): ...

    def get_files(): ...
